<?php

declare(strict_types=1);

class Item
{
    // Matches schema.sql's column definitions - kept here so every write
    // path truncates to the same limits instead of finding out about them
    // one "Data too long" mysqli_sql_exception at a time. fullText/fullHTML
    // are LONGTEXT (4GB) - no realistic page gets remotely close, so they're
    // not guarded here.
    private const MAX_URL_LENGTH = 767;
    private const MAX_TYPE_LENGTH = 50;
    private const MAX_TITLE_LENGTH = 255;
    private const MAX_KEYWORDS_LENGTH = 255;
    // description is TEXT (65,535 bytes) - utf8mb4's worst case is 4
    // bytes/char, so this is a safe character-count ceiling with headroom.
    private const MAX_DESCRIPTION_LENGTH = 16000;

    // How long a claim on an item lasts before it's considered abandoned and
    // becomes pickable again - comfortably longer than
    // bin/crawler-manager.php's hang-kill timeout, so a worker that gets
    // SIGKILLed mid-crawl frees its item up again on its own rather than
    // leaving it stuck until some other explicit cleanup.
    private const CLAIM_WINDOW_SECONDS = 300;

    // How many times nextToCrawl() will retry after losing a claim race to
    // another concurrent worker before giving up and returning null - under
    // normal contention (a handful of workers) losing more than a couple of
    // races in a row would be exceptional, not routine.
    private const MAX_CLAIM_ATTEMPTS = 10;

    // How long a just-crawled item waits before it's eligible again - the
    // starting point, not a fixed rule. Each recrawl that finds the content
    // unchanged doubles the wait (up to the max below), and one that finds
    // it changed resets to this. A page edited daily and a page untouched
    // since 1998 shouldn't be revisited on the same schedule, and the
    // content hash is how the queue learns which is which.
    private const RECRAWL_BASE_SECONDS = 7 * 24 * 60 * 60;
    private const RECRAWL_MAX_SECONDS = 8 * 7 * 24 * 60 * 60;

    // Rows per batched statement, so one page's discoveries can't build a
    // statement with thousands of parameters.
    private const BATCH_CHUNK_SIZE = 200;

    public ?int $itemId = null;
    public ?string $url = null;
    public ?int $hostId = null;
    public ?string $type = null;
    public ?string $title = null;
    public ?string $description = null;
    public ?string $keywords = null;
    public ?string $fullText = null;
    public ?string $fullHTML = null;
    public ?int $crawledTime = null;
    public ?int $noindex = null;
    public ?string $contentHash = null;
    public ?int $recrawlAfterSeconds = null;
    // Generated by the database (crawledTime + recrawlAfterSeconds) - never
    // written from here, only read.
    public ?int $recrawlDueTime = null;
    public ?int $claimedUntil = null;
    public ?int $inc = null;

    /**
     * fullText/fullHTML are only present when the row was read by something
     * that actually wants them (see findById() vs findWithContentById()), so
     * they're read leniently rather than assumed - every other column is
     * always selected.
     */
    public static function fromRow(array $row): self
    {
        $item = new self();

        $item -> itemId = (int) $row['itemId'];
        $item -> url = $row['url'];
        $item -> hostId = (int) $row['hostId'];
        $item -> type = $row['type'];
        $item -> title = $row['title'];
        $item -> description = $row['description'];
        $item -> keywords = $row['keywords'];
        $item -> fullText = $row['fullText'] ?? null;
        $item -> fullHTML = $row['fullHTML'] ?? null;
        $item -> crawledTime = $row['crawledTime'] !== null ? (int) $row['crawledTime'] : null;
        $item -> noindex = (int) $row['noindex'];
        $item -> contentHash = $row['contentHash'];
        $item -> recrawlAfterSeconds = (int) $row['recrawlAfterSeconds'];
        $item -> recrawlDueTime = $row['recrawlDueTime'] !== null ? (int) $row['recrawlDueTime'] : null;
        $item -> claimedUntil = $row['claimedUntil'] !== null ? (int) $row['claimedUntil'] : null;
        $item -> inc = (int) $row['inc'];

        return $item;
    }

    /**
     * The next item for the crawler to fetch, picked in three priority
     * classes (see selectCandidateRow()): never-crawled items first, then
     * recrawls whose wait has elapsed, most-overdue first, then stalled
     * claims last.
     *
     * $topic turns this into a focused crawl: among not-yet-crawled items,
     * the one whose *discovery context* - the Links.description text of
     * whichever page(s) linked to it - best matches $topic via FULLTEXT
     * MATCH/AGAINST goes first, rather than whatever happened to be
     * discovered earliest. An item can be linked from several parents with
     * different link text, so this takes the best-scoring one (MAX), not an
     * average - one strongly on-topic mention should outweigh several
     * unrelated ones. Falls back to the default order for recrawls
     * (everything already crawled once) or when nothing is left unqueued.
     *
     * Both queries also only consider items whose host is actually ready to
     * be hit again (Hosts.nextCrawlTime NULL - never crawled - or already in
     * the past) - politeness applies before anything else, focused crawl or
     * not - and whose claim (see claim()) has either never been taken or has
     * expired, so multiple concurrent crawler processes never hand the same
     * item to two workers at once.
     *
     * A never-attempted item always comes ahead of one whose claim expired
     * without completing (crawledTime still NULL despite claimedUntil being
     * set) - a worker that got SIGKILLed mid-crawl shouldn't cut in front of
     * the entire backlog of untried items the moment its claim lapses. It's
     * retried only once every fresh item and every due recrawl is exhausted
     * - which in a continuously-running crawl may never actually happen.
     *
     * Picking a row and claiming it are two separate statements (a plain
     * SELECT has no way to also lock/reserve what it reads), so there's a
     * window where a concurrent caller could win the claim first - claim()
     * reports that via its return value, and the loop here just retries
     * against a fresh SELECT (which will no longer include the
     * now-claimed-elsewhere row) rather than assuming its own pick still
     * stands.
     */
    public static function nextToCrawl(?string $topic = null): ?self
    {
        for ($attempt = 0; $attempt < self::MAX_CLAIM_ATTEMPTS; $attempt++) {
            $row = self::selectCandidateRow($topic);

            if ($row === null) {
                return null;
            }

            // The host's turn is taken before the item is claimed, and both
            // races are handled the same way - go back for a different row.
            // The candidate query filters on the host being due, so the next
            // attempt can't pick the same host again; losing here just means
            // a concurrent worker is already crawling something else on it.
            if (!Host::reserveById((int) $row['hostId'])) {
                continue;
            }

            if (self::claim((int) $row['itemId'])) {
                // The full row is fetched by primary key only now, after the
                // claim - the candidate query deliberately never touches the
                // wide columns (see selectCandidateRow()), and a row deleted
                // in the gap just means another spin of the loop.
                $item = self::findById((int) $row['itemId']);

                if ($item !== null) {
                    return $item;
                }
            }
        }

        return null;
    }

    /**
     * Only itemId and hostId come back from here - never `Items`.*. The
     * winner's full row is one primary-key lookup afterwards (see
     * nextToCrawl()); the wide columns have no business anywhere near the
     * picking itself.
     *
     * The pick runs as three separate index-driven queries in priority order
     * rather than one query whose ORDER BY encodes the priorities. The
     * single-query form sorted every eligible row through a temporary table
     * on every pick - a full Hosts scan fanned out to ~15k rows here - and
     * the sort was almost entirely wasted work, since the priority classes
     * were already known: fresh items first (their order among themselves
     * was never defined), then recrawls oldest-first (which the crawledTime
     * index yields for free, no sort), then stalled claims last. Each class
     * stops at the first eligible row it finds.
     */
    private static function selectCandidateRow(?string $topic): ?array
    {
        $connection = Database::connection();

        if ($topic !== null && trim($topic) !== '') {
            $row = self::selectFocusedCandidateRow($topic);

            if ($row !== null) {
                return $row;
            }
        }

        // Never-attempted items, driven from the (small) Hosts side: for each
        // due host, one probe of the hostId_crawledTime_claimedUntil index
        // answers "any uncrawled, unclaimed item here?".
        $fresh = mysqli_query($connection, '
SELECT `Items`.`itemId`, `Items`.`hostId`
    FROM `Hosts`
    INNER JOIN `Items` ON `Items`.`hostId` = `Hosts`.`hostId` AND `Items`.`crawledTime` IS NULL
    WHERE (`Hosts`.`nextCrawlTime` IS NULL OR `Hosts`.`nextCrawlTime` <= UNIX_TIMESTAMP())
        AND `Items`.`claimedUntil` IS NULL
    LIMIT 1
');
        $row = $fresh !== false ? mysqli_fetch_assoc($fresh) : null;

        if ($row !== null) {
            return $row;
        }

        // Recrawls, most-overdue first. recrawlDueTime (a stored generated
        // column: crawledTime + recrawlAfterSeconds) makes due-ness an
        // indexed range rather than per-row arithmetic - the alternative
        // walked crawled rows until one passed the math, and walked all of
        // them on every pick whenever none did. The index range reads only
        // rows that are actually due, already in due order.
        $recrawl = mysqli_query($connection, '
SELECT STRAIGHT_JOIN `Items`.`itemId`, `Items`.`hostId`
    FROM `Items` FORCE INDEX (`recrawlDueTime_claimedUntil_hostId`)
    INNER JOIN `Hosts` FORCE INDEX (`PRIMARY`) ON `Hosts`.`hostId` = `Items`.`hostId`
    WHERE `Items`.`recrawlDueTime` <= UNIX_TIMESTAMP()
        AND (`Items`.`claimedUntil` IS NULL OR `Items`.`claimedUntil` <= UNIX_TIMESTAMP())
        AND (`Hosts`.`nextCrawlTime` IS NULL OR `Hosts`.`nextCrawlTime` <= UNIX_TIMESTAMP())
    ORDER BY `Items`.`recrawlDueTime` ASC
    LIMIT 1
');
        $row = $recrawl !== false ? mysqli_fetch_assoc($recrawl) : null;

        if ($row !== null) {
            return $row;
        }

        // Stalled items - a claim was taken but never completed (a killed
        // worker). Deliberately dead last: a URL that already ate one worker
        // shouldn't cut ahead of anything untried.
        $stalled = mysqli_query($connection, '
SELECT `Items`.`itemId`, `Items`.`hostId`
    FROM `Hosts`
    INNER JOIN `Items` ON `Items`.`hostId` = `Hosts`.`hostId` AND `Items`.`crawledTime` IS NULL
    WHERE (`Hosts`.`nextCrawlTime` IS NULL OR `Hosts`.`nextCrawlTime` <= UNIX_TIMESTAMP())
        AND `Items`.`claimedUntil` IS NOT NULL
        AND `Items`.`claimedUntil` <= UNIX_TIMESTAMP()
    LIMIT 1
');

        return $stalled !== false ? mysqli_fetch_assoc($stalled) : null;
    }

    /**
     * The focused-crawl pick: among not-yet-crawled items, the one whose
     * discovery context best matches the topic. Driven from the Links
     * FULLTEXT index inward - only links whose text actually matches are
     * grouped and scored, instead of every uncrawled item LEFT-JOINing its
     * whole link set just so non-matches could sort behind matches. An item
     * with no matching link at all is simply not this query's business:
     * returning null lets the default order take over, which is also what
     * happens once the on-topic pool is exhausted.
     */
    private static function selectFocusedCandidateRow(string $topic): ?array
    {
        $focused = mysqli_prepare(Database::connection(), '
SELECT `Items`.`itemId`, `Items`.`hostId`
    FROM (
        SELECT `Links`.`childId`, MAX(MATCH(`Links`.`description`) AGAINST (?)) AS `score`
            FROM `Links`
            WHERE MATCH(`Links`.`description`) AGAINST (?)
            GROUP BY `Links`.`childId`
    ) AS `matches`
    INNER JOIN `Items` ON `Items`.`itemId` = `matches`.`childId`
    INNER JOIN `Hosts` ON `Hosts`.`hostId` = `Items`.`hostId`
    WHERE `Items`.`crawledTime` IS NULL
        AND (`Hosts`.`nextCrawlTime` IS NULL OR `Hosts`.`nextCrawlTime` <= UNIX_TIMESTAMP())
        AND (`Items`.`claimedUntil` IS NULL OR `Items`.`claimedUntil` <= UNIX_TIMESTAMP())
    ORDER BY (`Items`.`claimedUntil` IS NOT NULL) ASC, `matches`.`score` DESC, `Items`.`itemId` ASC
    LIMIT 1
');
        mysqli_stmt_bind_param($focused, 'ss', $topic, $topic);
        mysqli_stmt_execute($focused);

        return mysqli_fetch_assoc(mysqli_stmt_get_result($focused));
    }

    /**
     * The item with this id, or null if there isn't one - for the callers
     * that already have an id in hand rather than one of the queue's own
     * picks (bin/crawler-manager.php identifying the item a killed worker was
     * stuck on, api/delete-item.php).
     *
     * Everything except fullText and fullHTML. Those two are the entire page,
     * routinely megabytes, and no caller of this reads them: the crawler
     * loads the item it is about to overwrite, and the manager loads one it
     * is about to delete. Dragging them across the wire per pick was pure
     * cost. findWithContentById() is the one for a caller that wants them.
     */
    public static function findById(int $itemId): ?self
    {
        $select = mysqli_prepare(Database::connection(), '
SELECT `itemId`, `url`, `hostId`, `type`, `title`, `description`, `keywords`,
        `crawledTime`, `noindex`, `contentHash`, `recrawlAfterSeconds`, `recrawlDueTime`,
        `claimedUntil`, `inc`
    FROM `Items`
    WHERE `itemId` = ?
    LIMIT 1
');
        mysqli_stmt_bind_param($select, 'i', $itemId);
        mysqli_stmt_execute($select);
        $row = mysqli_fetch_assoc(mysqli_stmt_get_result($select));

        return $row !== null ? self::fromRow($row) : null;
    }

    /**
     * findById() plus the stored page content, for the one caller that
     * genuinely re-reads it (bin/reextract-text.php).
     */
    public static function findWithContentById(int $itemId): ?self
    {
        $select = mysqli_prepare(Database::connection(), '
SELECT *
    FROM `Items`
    WHERE `itemId` = ?
    LIMIT 1
');
        mysqli_stmt_bind_param($select, 'i', $itemId);
        mysqli_stmt_execute($select);
        $row = mysqli_fetch_assoc(mysqli_stmt_get_result($select));

        return $row !== null ? self::fromRow($row) : null;
    }

    /**
     * Claims this item the same way nextToCrawl() does, for the case where a
     * worker ends up holding an item it never went through nextToCrawl() to
     * get - specifically a redirect that lands on a pre-existing item (see
     * redirectTo() and bin/crawler.php's redirect loop). Returns false if
     * another worker already holds a live claim on it, so the caller can bow
     * out rather than double-crawl the same URL.
     */
    public function reclaim(): bool
    {
        return self::claim($this -> itemId);
    }

    /**
     * Atomically reserves $itemId for CLAIM_WINDOW_SECONDS - the WHERE here
     * re-checks the same claimedUntil condition selectCandidateRow() already
     * filtered on, so this UPDATE only actually claims the row (affected
     * rows > 0) if no other concurrent caller claimed it first in the gap
     * between that SELECT and this UPDATE.
     */
    private static function claim(int $itemId): bool
    {
        $connection = Database::connection();
        $claimedUntil = time() + self::CLAIM_WINDOW_SECONDS;

        $update = mysqli_prepare($connection, '
UPDATE `Items`
    SET `claimedUntil` = ?
    WHERE `itemId` = ?
        AND (`claimedUntil` IS NULL OR `claimedUntil` <= UNIX_TIMESTAMP())
');
        mysqli_stmt_bind_param($update, 'ii', $claimedUntil, $itemId);
        mysqli_stmt_execute($update);

        return mysqli_stmt_affected_rows($update) > 0;
    }

    /**
     * Finds the existing Item for a URL (the same image/page is routinely
     * linked from many different pages - it should be one row with many
     * Links rows pointing at it, not a duplicate per page it's found on) or
     * creates one if this is the first time this URL has been seen - as a
     * single INSERT ... ON DUPLICATE KEY UPDATE against the url unique key,
     * rather than a SELECT to check followed by a separate INSERT. The
     * UPDATE bumps inc (a reference count - how many times this URL has been
     * seen/linked) rather than crawledTime: crawledTime means "actually
     * fetched", and being merely rediscovered as a link isn't that - touching
     * it here would make a frequently-linked-but-never-fetched item look
     * freshly crawled and starve it out of nextToCrawl()'s queue. inc always
     * changes (it's a genuine +1 every time, never a coincidental repeat), so
     * it also keeps this a real write rather than a no-op - which is what
     * makes mysqli_insert_id() return the existing row's itemId at all.
     *
     * Returns null instead when this URL shouldn't enter the queue at all:
     * it's already been resolved as dead (DeadURL - without this, deleting a
     * 404 just means rediscovering, refetching and redeleting it on every
     * recrawl of anything that links to it), or its host already has more
     * queued than it can work through (Host::hasPendingCapacity()). Callers
     * discovering links are expected to simply skip those.
     */
    public static function findOrCreateByURL(URL $url, string $type, ?string $title = null, ?string $description = null): ?self
    {
        $connection = Database::connection();
        $urlString = self::truncate($url -> toString(), self::MAX_URL_LENGTH);
        $type = self::truncate($type, self::MAX_TYPE_LENGTH);
        $title = self::truncate($title, self::MAX_TITLE_LENGTH);
        $description = self::truncate($description, self::MAX_DESCRIPTION_LENGTH);

        if (DeadURL::isDead($urlString)) {
            return null;
        }

        $host = Host::findOrCreateByName($url -> host);

        if (!$host -> hasPendingCapacity()) {
            return null;
        }

        // A rediscovery fills in a title/description the row doesn't have yet
        // - COALESCE keeps whatever's already there, so nothing a crawl
        // extracted (or an earlier link supplied) is ever overwritten, but a
        // row created from a bare href with no text does pick up the first
        // real description some later link gives it.
        //
        // inc is untouched here, and starts at zero. It counts the distinct
        // pages that link to a URL, and this path is for URLs that arrived
        // some other way entirely - a sitemap entry or an operator's seed,
        // neither of which is anybody linking to anything. Bumping it per
        // call would also let a sitemap listing the same URL repeatedly raise
        // it once a week for free. LAST_INSERT_ID() on the duplicate branch
        // keeps mysqli_insert_id() returning the existing row's id without a
        // counter being incremented to force it.
        $insert = mysqli_prepare($connection, '
INSERT INTO `Items` (`url`, `hostId`, `type`, `title`, `description`, `inc`)
    VALUES (?, ?, ?, ?, ?, 0)
    ON DUPLICATE KEY UPDATE
        `itemId` = LAST_INSERT_ID(`itemId`),
        `title` = COALESCE(`title`, VALUES(`title`)),
        `description` = COALESCE(`description`, VALUES(`description`))
');
        mysqli_stmt_bind_param($insert, 'sisss', $urlString, $host -> hostId, $type, $title, $description);
        mysqli_stmt_execute($insert);

        // 1 affected row means a genuine INSERT, 2 means the ON DUPLICATE KEY
        // branch bumped an existing row - only the first added anything to
        // the queue, and only that should count against the host's cap.
        if (mysqli_stmt_affected_rows($insert) === 1) {
            $host -> countNewPendingItem();
        }

        $item = new self();
        $item -> itemId = (int) mysqli_insert_id($connection);
        $item -> url = $urlString;
        $item -> hostId = $host -> hostId;
        $item -> type = $type;
        $item -> title = $title;
        $item -> description = $description;

        return $item;
    }

    /**
     * The batched form of findOrCreateByURL(), for a whole page's discovered
     * links at once - returns url => Item for everything that entered the
     * queue, omitting whatever was skipped (already dead, or its host at
     * capacity), exactly as the single-URL form returns null for those.
     *
     * Same outcome as calling findOrCreateByURL() per link, in a handful of
     * statements instead of five per link. A page linking a few hundred URLs
     * was spending seconds of round trips here - more than parsing the page
     * and, on a fast host, more than fetching it.
     *
     * $discoveries is url => ['url' => URL, 'type' => string,
     * 'description' => ?string, 'count' => int]. count is 1 per discovered
     * URL - a page mentioning the same target ten times is one page linking
     * it - and only feeds Hosts.inc; Items.inc is raised separately, by
     * countInboundLinks(), off the link edges that were actually new.
     *
     * @return array<string, self>
     */
    public static function findOrCreateManyByURL(array $discoveries): array
    {
        if ($discoveries === []) {
            return [];
        }

        $connection = Database::connection();

        // Stored form first, exactly as the single-URL path does: url is
        // varchar(767) and a longer one is a hard error, not a warning. The
        // caller's own key is carried alongside so the returned map still
        // answers to what it asked about; two callers' URLs that truncate to
        // the same stored string are the same row, first key winning.
        $stored = [];

        foreach ($discoveries as $urlString => $discovery) {
            $storedURL = self::truncate($urlString, self::MAX_URL_LENGTH);

            if (isset($stored[$storedURL])) {
                $stored[$storedURL]['count'] += $discovery['count'];
                continue;
            }

            $stored[$storedURL] = ['key' => $urlString, 'discovery' => $discovery, 'count' => $discovery['count']];
        }

        $dead = DeadURL::deadAmong(array_keys($stored));
        $hostCounts = [];

        foreach ($stored as $storedURL => $entry) {
            if (isset($dead[$storedURL])) {
                continue;
            }

            $hostName = $entry['discovery']['url'] -> host;
            $hostCounts[$hostName] = ($hostCounts[$hostName] ?? 0) + $entry['count'];
        }

        $hosts = Host::findOrCreateManyByName($hostCounts);
        $pending = [];

        foreach ($stored as $storedURL => $entry) {
            if (isset($dead[$storedURL])) {
                continue;
            }

            $host = $hosts[$entry['discovery']['url'] -> host] ?? null;

            if ($host === null || !$host -> hasPendingCapacity()) {
                continue;
            }

            $host -> countNewPendingItem();
            $pending[$storedURL] = ['discovery' => $entry['discovery'], 'host' => $host, 'key' => $entry['key'], 'count' => $entry['count']];
        }

        if ($pending === []) {
            return [];
        }

        foreach (array_chunk($pending, self::BATCH_CHUNK_SIZE, true) as $chunk) {
            $rows = implode(', ', array_fill(0, count($chunk), '(?, ?, ?, ?, ?, 0)'));
            $arguments = [];
            $types = '';

            foreach ($chunk as $storedURL => $entry) {
                $arguments[] = $storedURL;
                $arguments[] = $entry['host'] -> hostId;
                $arguments[] = self::truncate($entry['discovery']['type'], self::MAX_TYPE_LENGTH);
                $arguments[] = self::truncate($entry['discovery']['title'] ?? null, self::MAX_TITLE_LENGTH);
                $arguments[] = self::truncate($entry['discovery']['description'], self::MAX_DESCRIPTION_LENGTH);
                $types .= 'sisss';
            }

            // inc is not touched here. Discovering a URL is not the same
            // event as a new page linking to it: a recrawl rediscovers every
            // link the page already had, so counting those would let a site
            // raise any URL's score forever just by being recrawled.
            // countInboundLinks() does the counting, off the link edges that
            // turn out to be genuinely new.
            $insert = mysqli_prepare($connection, '
INSERT INTO `Items` (`url`, `hostId`, `type`, `title`, `description`, `inc`)
    VALUES ' . $rows . '
    ON DUPLICATE KEY UPDATE
        `title` = COALESCE(`title`, VALUES(`title`)),
        `description` = COALESCE(`description`, VALUES(`description`))
');
            mysqli_stmt_bind_param($insert, $types, ...$arguments);
            mysqli_stmt_execute($insert);
        }

        $items = [];

        // Items.url is a utf8mb4_unicode_ci column, so both the unique index
        // and the IN () below compare case-insensitively: a page linking
        // "/give-to-agu" when the row on file says "/Give-to-AGU" upserts
        // into that existing row and reads it back under the spelling the
        // *database* holds, not the one asked for. Looking $pending up by the
        // URL that comes back therefore misses, losing the link its edge.
        // Folding both sides makes this lookup agree with the matching the
        // database does.
        $byFoldedURL = [];

        foreach ($pending as $storedURL => $entry) {
            $byFoldedURL[mb_strtolower($storedURL)] = $entry;
        }

        foreach (array_chunk(array_keys($pending), self::BATCH_CHUNK_SIZE) as $chunk) {
            $placeholders = implode(', ', array_fill(0, count($chunk), '?'));

            // Without fullText/fullHTML: this reads back a whole page's worth
            // of freshly-upserted rows purely to learn their itemIds, and a
            // rediscovered URL that has already been crawled would otherwise
            // drag its entire stored page along for nothing.
            $select = mysqli_prepare($connection, '
SELECT `itemId`, `url`, `hostId`, `type`, `title`, `description`, `keywords`,
        `crawledTime`, `noindex`, `contentHash`, `recrawlAfterSeconds`, `recrawlDueTime`,
        `claimedUntil`, `inc`
    FROM `Items`
    WHERE `url` IN (' . $placeholders . ')
');
            mysqli_stmt_bind_param($select, str_repeat('s', count($chunk)), ...$chunk);
            mysqli_stmt_execute($select);
            $result = mysqli_stmt_get_result($select);

            while ($row = mysqli_fetch_assoc($result)) {
                // Keyed by the caller's original URL, not the stored one, so
                // a truncated URL still maps back to what was asked about.
                // A row that matched under a collation equivalence this
                // folding doesn't reproduce (utf8mb4_unicode_ci also folds
                // accents, and more besides) is dropped rather than keyed by
                // nothing - the caller never asked about it under any name it
                // would recognize.
                $entry = $byFoldedURL[mb_strtolower($row['url'])] ?? null;

                if ($entry !== null) {
                    $items[$entry['key']] = self::fromRow($row);
                }
            }
        }

        return $items;
    }

    /**
     * Counts one newly-recorded inbound link against each of $itemIds -
     * called with exactly the link edges Link::createMany() actually created,
     * so `inc` ends up meaning "how many distinct pages link here" rather
     * than "how many times has anything mentioned this URL".
     *
     * The distinction is the whole point of the column as a ranking signal.
     * Counted per mention, a single page raises the number by itself, by
     * repeating a link or simply by being recrawled - and a signal a page can
     * set about itself is not a signal.
     *
     * @param list<int> $itemIds
     */
    public static function countInboundLinks(array $itemIds): void
    {
        if ($itemIds === []) {
            return;
        }

        $connection = Database::connection();

        foreach (array_chunk($itemIds, self::BATCH_CHUNK_SIZE) as $chunk) {
            $placeholders = implode(', ', array_fill(0, count($chunk), '?'));

            $update = mysqli_prepare($connection, '
UPDATE `Items`
    SET `inc` = `inc` + 1
    WHERE `itemId` IN (' . $placeholders . ')
');
            mysqli_stmt_bind_param($update, str_repeat('i', count($chunk)), ...$chunk);
            mysqli_stmt_execute($update);
        }
    }

    /**
     * Records that this item has actually been fetched and processed - the
     * real Content-Type (replacing whatever placeholder guess got it
     * created, e.g. "image" or "unknown"), the extracted title/description/
     * keywords/fullText/fullHTML, and crawledTime stamped to now. This is
     * always the last step of crawling something: crawledTime is what
     * nextToCrawl() orders by, so this is what actually moves the queue
     * forward past this item.
     *
     * The extracted text is hashed and compared against the previous crawl's
     * hash to set the next recrawl interval: unchanged content doubles the
     * wait, changed content resets it to the base - so the queue's recrawl
     * effort drifts toward the pages that actually change. Items without
     * text (images) hash to the same value every time and back off the same
     * way, which is right: an image at a URL almost never changes in place.
     *
     * $noindex records a page-level opt-out (meta robots / X-Robots-Tag):
     * still crawled, links still counted, but search never returns it.
     *
     * fullHTML is stored gzip-compressed - it's the whole raw page, kept
     * only for future re-processing, and it compresses to about a quarter.
     * decompressedFullHTML() is the matching reader.
     */
    public function markCrawled(string $type, ?string $title, ?string $description, ?string $keywords, ?string $fullText, ?string $fullHTML, int $noindex = 0): void
    {
        $connection = Database::connection();
        $now = time();

        $type = self::truncate($type, self::MAX_TYPE_LENGTH);
        $title = self::truncate($title, self::MAX_TITLE_LENGTH);
        $description = self::truncate($description, self::MAX_DESCRIPTION_LENGTH);
        $keywords = self::truncate($keywords, self::MAX_KEYWORDS_LENGTH);

        // Applied here rather than at each of the places text is extracted
        // (HTML body, PDF, plain text) because this is the one call all of
        // them end at - a cap a future content type could be added around is
        // no cap at all. See Text::capRepeatedTerms() for why an unbounded
        // term count decides rankings outright.
        $fullText = $fullText !== null ? Text::capRepeatedTerms($fullText) : null;

        // Hashed after capping, so the recrawl schedule compares what's
        // actually stored against what was actually stored last time.
        $contentHash = sha1((string) $fullText);
        $recrawlAfterSeconds = $contentHash === $this -> contentHash
            ? min(($this -> recrawlAfterSeconds ?? self::RECRAWL_BASE_SECONDS) * 2, self::RECRAWL_MAX_SECONDS)
            : self::RECRAWL_BASE_SECONDS;

        $storedFullHTML = $fullHTML !== null ? gzencode($fullHTML, 6) : null;

        $update = mysqli_prepare($connection, '
UPDATE `Items`
    SET `type` = ?, `title` = ?, `description` = ?, `keywords` = ?, `fullText` = ?, `fullHTML` = ?,
        `crawledTime` = ?, `noindex` = ?, `contentHash` = ?, `recrawlAfterSeconds` = ?
    WHERE `itemId` = ?
');
        mysqli_stmt_bind_param($update, 'ssssssiisii', $type, $title, $description, $keywords, $fullText, $storedFullHTML, $now, $noindex, $contentHash, $recrawlAfterSeconds, $this -> itemId);
        mysqli_stmt_execute($update);

        $this -> type = $type;
        $this -> title = $title;
        $this -> description = $description;
        $this -> keywords = $keywords;
        $this -> fullText = $fullText;
        $this -> fullHTML = $storedFullHTML;
        $this -> crawledTime = $now;
        $this -> noindex = $noindex;
        $this -> contentHash = $contentHash;
        $this -> recrawlAfterSeconds = $recrawlAfterSeconds;
        $this -> recrawlDueTime = $now + $recrawlAfterSeconds;
    }

    /**
     * The stored page HTML, decompressed. Rows written before compression
     * existed hold plain text - told apart by the gzip magic bytes, so both
     * generations read back correctly without a migration pass.
     */
    public function decompressedFullHTML(): ?string
    {
        if ($this -> fullHTML === null) {
            return null;
        }

        if (str_starts_with($this -> fullHTML, chr(0x1F) . chr(0x8B))) {
            $decoded = gzdecode($this -> fullHTML);

            return $decoded !== false ? $decoded : null;
        }

        return $this -> fullHTML;
    }

    /**
     * Removes this item outright - e.g. a redirect the crawler gave up on
     * (too many hops, a broken Location) rather than leaving a permanently
     * un-crawlable row sitting at crawledTime NULL, which nextToCrawl() would
     * otherwise keep handing back forever on every single run.
     *
     * $reason, when given, additionally records the URL as dead (DeadURL) so
     * rediscovering it doesn't just start the whole cycle again. Left null
     * for a deletion that isn't a verdict on the URL itself - an operator
     * clearing a row out of the index by hand, say, which shouldn't stop it
     * ever being crawled again.
     */
    public function delete(?string $reason = null): void
    {
        if ($reason !== null) {
            DeadURL::record($this -> url, $reason);
        }

        $delete = mysqli_prepare(Database::connection(), '
DELETE FROM `Items`
    WHERE `itemId` = ?
');
        mysqli_stmt_bind_param($delete, 'i', $this -> itemId);
        mysqli_stmt_execute($delete);

        // The row is what points at the thumbnail; with it gone the file is
        // unreachable, and nothing else would ever come back for it. itemIds
        // are never reused (AUTO_INCREMENT), so this can't take out a file
        // some later item would have wanted.
        ImageLoader::deleteThumbnail($this -> itemId);
    }

    /**
     * Repoints this item at a redirect target - the URL this item was
     * fetched under was wrong (a 301/302/etc pointed somewhere else), and
     * $newURL is what it should actually be. url is UNIQUE, so if some other
     * item already owns that URL (found separately, e.g. via a link), the
     * UPDATE fails with a duplicate-key error rather than succeeding: this
     * row never had any content of its own (it's just the old address), so
     * it's deleted and the caller gets back the item that already exists at
     * $newURL instead - the two would otherwise represent the same resource
     * under two different itemIds forever. Also repoints hostId - a redirect
     * can just as easily land on a different host entirely (a domain-wide
     * 301 to a new site, a CDN move, ...), not just add/drop a trailing
     * slash on the same one.
     */
    public function redirectTo(URL $newURL): ?self
    {
        $connection = Database::connection();
        $newURLString = self::truncate($newURL -> toString(), self::MAX_URL_LENGTH);
        $newHostId = Host::findOrCreateByName($newURL -> host) -> hostId;

        // A live redirect pointing here is the site itself saying this URL is
        // current, which is better evidence than whatever verdict was reached
        // about it earlier - and the item is about to exist at this URL
        // regardless, so a stale dead-URL entry would only block it from
        // being rediscovered later.
        DeadURL::forget($newURLString);

        try {
            $update = mysqli_prepare($connection, '
UPDATE `Items`
    SET `url` = ?, `hostId` = ?
    WHERE `itemId` = ?
');
            mysqli_stmt_bind_param($update, 'sii', $newURLString, $newHostId, $this -> itemId);
            mysqli_stmt_execute($update);

            $this -> url = $newURLString;
            $this -> hostId = $newHostId;

            return $this;
        } catch (\mysqli_sql_exception) {
            // Without the page content: the survivor is either about to be
            // crawled and overwritten, or reported as already crawled and
            // dropped. Neither reads what it currently stores.
            $select = mysqli_prepare($connection, '
SELECT `itemId`, `url`, `hostId`, `type`, `title`, `description`, `keywords`,
        `crawledTime`, `noindex`, `contentHash`, `recrawlAfterSeconds`, `recrawlDueTime`,
        `claimedUntil`, `inc`
    FROM `Items`
    WHERE `url` = ?
    LIMIT 1
');
            mysqli_stmt_bind_param($select, 's', $newURLString);
            mysqli_stmt_execute($select);
            $row = mysqli_fetch_assoc(mysqli_stmt_get_result($select));

            // The row that caused the duplicate-key failure can be gone again
            // by the time it's read back - another worker crawling the same
            // redirect target may have deleted it in between. Nothing was
            // lost (this item never had content of its own), so this reports
            // "no item" the same way any other dead end does.
            if ($row === null) {
                $this -> delete();

                return null;
            }

            // This row's link edges move to the survivor before the delete -
            // ON DELETE CASCADE would otherwise erase them, and every page
            // that linked the old URL is genuinely linking the resource that
            // now lives at the new one. That inbound-link count is a ranking
            // signal; a merge shouldn't quietly cost the survivor part of
            // its own score. Self-edges (the survivor linking the old URL,
            // or vice versa) are skipped - a page endorsing itself isn't a
            // signal, and Link::create() refuses them for the same reason.
            $survivorId = (int) $row['itemId'];

            $moveInbound = mysqli_prepare($connection, '
INSERT IGNORE INTO `Links` (`parentId`, `childId`, `description`)
    SELECT `parentId`, ?, `description`
        FROM `Links`
        WHERE `childId` = ?
            AND `parentId` <> ?
');
            mysqli_stmt_bind_param($moveInbound, 'iii', $survivorId, $this -> itemId, $survivorId);
            mysqli_stmt_execute($moveInbound);

            $moveOutbound = mysqli_prepare($connection, '
INSERT IGNORE INTO `Links` (`parentId`, `childId`, `description`)
    SELECT ?, `childId`, `description`
        FROM `Links`
        WHERE `parentId` = ?
            AND `childId` <> ?
');
            mysqli_stmt_bind_param($moveOutbound, 'iii', $survivorId, $this -> itemId, $survivorId);
            mysqli_stmt_execute($moveOutbound);

            $this -> delete();

            return self::fromRow($row);
        }
    }

    /**
     * mb_substr, not substr - these columns are utf8mb4, and cutting a
     * multi-byte character in half would either corrupt it or (depending on
     * exactly where the cut lands) still overflow the column. Truncating url
     * specifically is a last resort, not a fix - a cut-off URL points at a
     * different resource or nothing at all - but it's still better than this
     * throwing a mysqli_sql_exception and killing the whole crawl process
     * over one pathological page.
     */
    private static function truncate(?string $value, int $maxLength): ?string
    {
        return $value !== null ? mb_substr($value, 0, $maxLength) : null;
    }
}
